### ISSUE TITLE
%zu not supported in printf()

### ISSUE THREAD

**Issue by cspiegel** [tkchia/newlib-ia16#15]
The `%zu` specifier (introduced in C99) is not supported.  The following:

```c
#include <stdio.h>

int main(void)
{
    printf("%zu\n", (size_t)0);

    return 0;
}
```
just results in `zu` being printed.

I'm not sure if this is a gcc or newlib issue: it happens if I use `__builtin_printf` directly, but also happens if I pass `-fno-builtin-printf` to gcc.

This is from build-ia16 20201106.

**Comment by tkchia** [comment]
Hello @cspiegel,

I have uploaded an updated pre-compiled DJGPP-hosted toolchain ([20210305](https://github.com/tkchia/build-ia16/releases/tag/20210305)).  This update should resolve this issue and your previous issue (https://github.com/tkchia/newlib-ia16/issues/14).

Thank you!
