### ISSUE TITLE
Commit contains an int3 breakpoint

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/newlib-ia16#22]
Is this intended in this commit or just a debugging artefact?

https://github.com/tkchia/newlib-ia16/commit/55c79c8997101c55ac38ac1cacd47819e91a7563#diff-d0c883b67b7c4c4ba07c6efa1026c935505b519d3c5a43fd7cb608baae5e146dR51

**Comment by tkchia** [comment]
@ecm-pushbx : Oops.  Let me fix that.  Thanks for your report!

**Comment by tkchia** [comment]
@ecm-pushbx : This should be fixed now at https://github.com/tkchia/newlib-ia16/commit/81c3c13d7cadd1fa22432c2414a89ab86f101cd5 .  I will merge the "DPMI dual mode" changes into the main branch after the `libi86` tests pass.  Thank you!
